### ISSUE TITLE
Load_weights not working

### ISSUE THREAD

**Issue by cjmcmurtrie** [hycis/bidirectional_RNN#6]
It looks like there may be a problem with the load_weights method when trying to re-load the bi-directional model after a previous training session.

```
  File "D:/Final project/TimeNLPTest/KerasVec2Vec.py", line 130, in buildBiLSTM
    model.load_weights(dir + "StackedLSTM E-D 13 epochs 50 512 20 relu mse adam 2015-08-23 10.55.41.621000 .wt")
  File "C:\Anaconda\lib\site-packages\keras\models.py", line 492, in load_weights
    for k in range(f.attrs['nb_layers']):
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2475)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2432)
  File "C:\Anaconda\lib\site-packages\h5py\_hl\attrs.py", line 52, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2475)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (D:\Build\h5py\h5py-2.5.x\h5py\_objects.c:2432)
  File "h5py\h5a.pyx", line 77, in h5py.h5a.open (D:\Build\h5py\h5py-2.5.x\h5py\h5a.c:2079)
KeyError: "Can't open attribute (Can't locate attribute: 'nb_layers')"
```

I can try and work with you to sort this out, what do you think the problem could be?

**Comment by cjmcmurtrie** [comment]
To be clear the model I used when saving those weights was identitical to the one I used when loading them:

```
model = Sequential()
model.add(BiDirectionLSTM(embedding_size, hidden_size, init=initialize))
model.add(Dense(hidden_size, hidden_size, init=initialize))
model.add(Activation('relu'))
model.add(RepeatVector(maxlen))
model.add(LSTM(hidden_size, hidden_size, return_sequences=True, init=initialize))
model.add(TimeDistributedDense(hidden_size, output_size, activation='softmax', init=initialize))
```

**Comment by cjmcmurtrie** [comment]
Ignore this, I found the problem.

**Comment by TELSER1** [comment]
@cjmcmurtrie Could you clarify what the issue was?  I'm having a similar problem.

**Comment by bryan-lunt** [comment]
I have this same problem, and I'd like to know what the solution was.

**Comment by bryan-lunt** [comment]
@TELSER1 Non-Existant and/or 0 byte h5 file.

**Comment by erlizhou** [comment]
I also have this problem @cjmcmurtrie @bryan-lunt can you tell me the solution?

**Comment by hycis** [comment]
Maybe you can post your code up here, otherwise you may also wish to try out mozi bilstm
https://github.com/hycis/Mozi/blob/master/example/imdb_bilstm.py

**Comment by bryan-lunt** [comment]
I think it was that my h5 file was bad.

**Comment by bryan-lunt** [comment]
@erlizhou It was definitely a non-existant file.

**Comment by bryan-lunt** [comment]
I guess it needs a separate issue on the master branch, but it seems that load_weights will create the .h5 file if it doesn't exist.
I don't like that behavior.

**Comment by bryan-lunt** [comment]
I fixed this in my own keras repo.
https://github.com/bryan-lunt/keras/tree/fix_load_weights

You can comment on my pull-request on the main keras repo. 
https://github.com/fchollet/keras/pull/1736

**Comment by south-ocean** [comment]
@erlizhou I am also face this problem, do you solve it?

**Comment by south-ocean** [comment]
@bryan-lunt  Hello, I can't find the solution from the link that you give, can you say it again, thank you.

**Comment by bryan-lunt** [comment]
@south-ocean You can clone my forked git repo and see the difference between that branch and the master it was based off of. I haven't delt with Keras for quite a while. The problem I was facing (judging by my comments) was that I was trying to load an h5 file that did not exist.

**Comment by Hemanth-Mydugolam** [comment]
@cjmcmurtrie can you please give me brief about the error how to solve it.

**Comment by brianleegit** [comment]
@cjmcmurtrie  Hi, I also have the same problem, can you tell me how you fix it?

**Comment by bryan-lunt** [comment]
The fix to the problem I was having is right here:

https://github.com/bryan-lunt/keras/commit/c23579e059c9cd88a956b7eac9a69f7d7e276fc8

I believe that it's already been merged into the main branch of keras.

The problem ( _my problem_) was that if you asked for an hdf5 file that did not already exist, an empty one would be created automatically.

This change prevents that. If you don't want to change keras for that, you can write your own code that will check for the existence of the file before trying to load it with keras.

**Comment by yuyifan1991** [comment]
who solve the problem? who  can tell me ?
